name: PHP Quality Assurance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: xdebug  # Active Xdebug pour la couverture

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Linter
        run: composer lint

      - name: Run Static Analysis
        run: composer analyse

      - name: Run Tests (PHPUnit)
        run: composer test

      - name: Generate and Upload Coverage Report
        env:
          XDEBUG_MODE: coverage
        run: |
          vendor/bin/phpunit --coverage-html build/coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build/coverage/
